"""add_url_index

Revision ID: 0debc4edd9ea
Revises: 1d685801ac43
Create Date: 2026-02-14 06:15:32.935876
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0debc4edd9ea'
down_revision: str | None = '1d685801ac43'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_silver_posts_url', 'silver_posts', ['url'], unique=False, sqlite_where=sa.text('url IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_silver_posts_url', table_name='silver_posts', sqlite_where=sa.text('url IS NOT NULL'))
    # ### end Alembic commands ###
