apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: postgres
    access: proxy
    url: ${AGGRE_PG_HOST}:${AGGRE_PG_PORT}
    database: aggre
    user: ${AGGRE_PG_USER}
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 2
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: ${AGGRE_PG_PASSWORD}
    editable: false
