metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "6a67c39bbc45a56c74edbe48fba480265f12197faade1e134bb13c87059c4686"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "z1G0Smv/KcjE59PYS7VGGclMym40FdYxGA4G5eqVwzU="
metrics_token = "xIrlnzXWFgu9PMgU/LcpqYxa2EgMlaYYB0tp2Is9Oc4="
